title: Monty Panday
description: Final year Programming student at Deakin, currently working as Junior Analyst Programmer at Box Hill Institute. Graduating in July 2018, looking for a full time role.
show_downloads: true

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://montypanday.github.io" # change this to the base hostname & protocol for your site

google_analytics:
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: 

author: "Monty Panday"
image: /thumbnail-jumbo.png